spring.application.name=job-tracker-api
# Show SQL statements in console
spring.jpa.show-sql=true
# Format the SQL nicely
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_SECRET:change-me-in-production}
jwt.expiration=3600000
