spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/auth/**
        - id: application-service
          uri: ${APPLICATION_SERVICE_URL}
          predicates:
            - Path=/applications/**
server:
  port: 8080