apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: allow-application-to-postgres
  namespace: jobtracker-dev

spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgres-application

  policyTypes:
    - Ingress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: application-service
      ports:
        - protocol: TCP
          port: 5432