apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-application
  template:
    metadata:
      labels:
        app: postgres-application
    spec:
      containers:
        - name: postgres-application
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-application-secret
          env:
            - name: POSTGRES_DB
              value: application_service
          volumeMounts:
            - name: postgres-application-storage
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            periodSeconds: 5
            failureThreshold: 3
          startupProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            failureThreshold: 15
            periodSeconds: 2
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
      volumes:
        - name: postgres-application-storage
          persistentVolumeClaim:
            claimName: postgres-application-pvc
