apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-application-service-config"
data:
  APPLICATION_SERVICE_DB_URL: jdbc:postgresql://blue-postgres-postgres-application-service:5432/application_service