apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-application-service"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: application-service
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  ports:
    - port: 8082
      targetPort: 8082